title: Kushaj
description: Kushajveer Singh personal websites
theme: just-the-docs

favicon_ico: /assets/images/favicon.ico

url: https://kushaj.com/

mermaid:
  version: "11.4.1"

color_scheme: dark
enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

source: docs
defaults:
  - values:
      layout: default
