site_name: Notes
site_url: https://kushajveersingh.com/notes/
site_author: Kushajveer Singh
site_description: Collection of personal notes for various technologies that I use on a daily basis.

repo_name: KushajveerSingh/notes
repo_url: https://github.com/KushajveerSingh/notes

copyright: Copyright &copy; 2023 - Present Kushajveer Singh

edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: '(prefers-color-scheme: dark)'
      primary: brown
      accent: yellow
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      primary: indigo
      accent: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.jpeg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - do_not_use_glitchbox
      auto_caption: true
      caption_position: bottom
  - table-reader
  - mkdocs-nav-weight:
      index_weight: 0
      section_renamed: true

extra:
  analytics:
    provider: google
    property: G-FXFJECD70Y
  social:
    - icon: material/home
      link: https://kushajveersingh.com
      name: Personal Website
    - icon: material/github
      link: https://github.com/KushajveerSingh
      name: GitHub
    - icon: material/linkedin
      link: https://linkedin.com/in/kushaj
      name: LinkedIn
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - abbr

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

nav:
  - Overview: index.md
  - Prompting:
    - ChatGPT: prompting/chatgpt.md
  - Documentation:
    - MkDocs: documentation/mkdocs.md
  - UI/UX:
    - Figma: ui_ux/figma.md
    - Logo Design: ui_ux/logo_design.md
    - Affinity Designer: ui_ux/affinity_designer.md
    - Books:
      - Don't Make Me Think: ui_ux/books/dont_make_me_think.md
      - Forms That Word: ui_ux/books/forms_that_work.md
  - HTML:
    - Images: html/images.md
  - CSS:
    - Tailwind CSS: css/tailwind_css.md
  - React:
    - Next.js: react/nextjs.md
  - Go:
    - Books:
      - Let's Go: go/books/lets_go.md
  - Postgres:
    - Postgres: postgres/postgres.md
